### ISSUE TITLE
Grid Not Recognized by Terms in 9.7

### ISSUE THREAD

**Issue by midiguru** [monome/Terms#3]
I'm using Windows 7 64-bit. When I plugged in my grid, Windows installed the drivers, or claimed it had done so. However, the grid doesn't show up in Device Manager. In any case, Terms can't find a grid connected to my computer. Is there some way I can figure out whether the problem is with the USB driver for grid, or whether it's with Terms under Live 9.7? Suggestions welcome (can be sent to midiguru23@sbcglobal.net). Thanks!

**Comment by tehn** [comment]
this is an installation issue, not a problem with terms directly. will debug via e-mail
